### ISSUE TITLE
JSON to XML - Out of spec XML generation

### ISSUE THREAD

**Issue by joaoismael** [engswee/equalize-cpi-converter#17]
Hi,

When converting JSON to XML

The following JSON key-pair 
`"first_name": "　\bHazel",`
Gets escaped and converted into:
`<first_name>　&#x8;Hazel</first_name>`

However, this is only valid on XML 1.1. As there is no VERSION populated on the DocumentBuilder, invalid XML is rendered:
`<?xml version="1.0" encoding="UTF-8">`

Thanks

**Comment by engswee** [comment]
Could you provide a sample input payload and the configuration parameters for the converter, so that I can try to reproduce the issue?

**Comment by engswee** [comment]
Closing issue as there is no example provided

**Comment by joaoismael** [comment]
I just wanted to make sure this doesn't go unanswered. The example provided is clear and should be sufficient for tracing the issue, should there be a genuine interest in addressing it.
